# Generated by Django 4.1.7 on 2023-04-17 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        default="profile_images/default.jpg", upload_to="profile_images"
                    ),
                ),
                (
                    "discord_id",
                    models.CharField(blank=True, max_length=30, verbose_name="Discord"),
                ),
                (
                    "pontuacao",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Pontuação"
                    ),
                ),
                (
                    "utilizador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Perfis",
            },
        ),
    ]
