# Generated by Django 4.1.7 on 2023-04-10 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("principal", "0002_jogador_delete_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        default="default.jpg", upload_to="profile_images"
                    ),
                ),
                ("Nome", models.CharField(blank=True, max_length=30)),
                (
                    "discord_id",
                    models.CharField(blank=True, max_length=30, verbose_name="Discord"),
                ),
                (
                    "pontuacao",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Pontuação"
                    ),
                ),
                (
                    "utilizador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="servico",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="Jogador",
        ),
    ]
