# Generated by Django 4.1.7 on 2023-04-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0003_perfil_alter_servico_id_delete_jogador"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Perfil",
        ),
    ]
